server:
  port: 8080
logging:
  config: classpath:logback.xml
spring:
  application:
    name: explorer
  aop:
    proxy-target-class: true
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://127.0.0.1:3306/explorer?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;characterSetResults=utf8&amp;connectionCollation=utf8_general_ci&allowMultiQueries=true&useSSL=false
    username: explorer
    password: 123456
    separator: ;
    name: explorer
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorer
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 1
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
mybatis:
  executor-type: simple
  type-aliases-package: io.nebulas.explorer.domain
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
grpc:
  host: 35.182.48.19
  port: 8684
  enableKeepAlive: true
  keepAliveWithoutCalls: true
  keepAliveTimeout: 2
page:
  baseUrl: http://localhost:8080
  hostUrl: http://localhost:8080
sync:
  zone: 100000
  cpu: 1
  open: true
  subscribe : true
apiHost:
  coinmarketcap: https://api.coinmarketcap.com
  nebulas: http://35.182.48.19:8685
redis:
  host: 127.0.0.1
  port: 6379
  password:

---
spring:
  profiles: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
environment: dev

---
spring:
  profiles: test
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://nebulas.cvajxeo2mhiu.us-west-1.rds.amazonaws.com:3306/explorer_test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;characterSetResults=utf8&amp;connectionCollation=utf8_general_ci&allowMultiQueries=true&useSSL=false
    username: explorer
    password: NbVgE6bQ8iM,(Aty5HBs
    separator: ;
    name: expltest
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorer
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 1
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
server:
  port: 32736
environment: test
page:
  baseUrl: http://52.53.225.118
  hostUrl: http://52.53.225.118

---
spring:
  profiles: prod
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
environment: production
