server:
  port: 8080
logging:
  config: classpath:logback.xml
flyway:
  baseline-on-migrate: true
spring:
  application:
    name: explorer
  aop:
    proxy-target-class: true
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://127.0.0.1:3306/explorer?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=round&characterEncoding=UTF-8&yearIsDateType=false
    username: explorer
    password: 123456
    separator: ;
    name: explorer
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorer
      maximum-pool-size: 30
      allow-pool-suspension: true
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 10
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
mybatis:
  executor-type: simple
  type-aliases-package: io.nebulas.explorer.domain
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
grpc:
  host: 47.92.203.173
  port: 8684
  enableKeepAlive: true
  keepAliveWithoutCalls: true
  keepAliveTimeout: 2
page:
  baseUrl: http://localhost:8080
  hostUrl: http://localhost:8080
sync:
  open: true
  subscribe: true
apiHost:
  coinmarketcap: https://api.coinmarketcap.com
  nebulas: https://testnet.nebulas.io
  gateio: https://data.gateio.io
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 2
environment: dev
pendingTxExpiredTime: 1
nax:
  contract:
    data: n1mVD6ZNVtuMCkwsVHvut7cDKna61DQY35X
    stakingProxy: n1kVgRwg5TJVZeEChr5BgGsFrSUUtJuHEHe
  topic: chain.contract.19586dcd5af213c856763d7703118f83406b24a72b5a8e554b28.NAX
  height:
    start: 2454300
    stage: 20


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.16.15.117:3306/explorer_test?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=round&characterEncoding=UTF-8&yearIsDateType=false
    username: root
    password: root@mysql
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 2
environment: dev
pendingTxExpiredTime: 1
grpc:
  host: 47.92.203.173
  port: 8684
  enableKeepAlive: true
  keepAliveWithoutCalls: true
  keepAliveTimeout: 2

#apiHost:
#  coinmarketcap: https://api.coinmarketcap.com
## 测试私链，用于测试DIP交易的解析
#  nebulas: http://47.92.203.173:9685
#  gateio: https://data.gateio.io

---
spring:
  profiles: test
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://127.0.0.1:3306/explorer_test?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=round&characterEncoding=UTF-8&yearIsDateType=false
    username: explorer
    password: kl@fkddfkFsa
    separator: ;
    name: expltest
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorer
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 1
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
server:
  port: 8080
environment: test
page:
  baseUrl: http://52.53.225.118
  hostUrl: http://52.53.225.118
pendingTxExpiredTime: 1
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 2
apiHost:
  coinmarketcap: https://api.coinmarketcap.com
  nebulas: http://47.92.203.173:8685
  gateio: https://data.gateio.io
grpc:
  host: 47.92.203.173
  port: 8684
  enableKeepAlive: true
  keepAliveWithoutCalls: true
  keepAliveTimeout: 2
---
spring:
  profiles: prod
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
environment: production
pendingTxExpiredTime: 48
